### ISSUE TITLE
ERR_CHILD_PROCESS_STDIO_MAXBUFFER error when running

### ISSUE THREAD

**Issue by DrewRomanyk** [svenheden/csharp-models-to-typescript#22]
When running on node v11.13.0, I am getting the error below. However if I set the maxBuffer higher for this line:
```
exec(`dotnet run --project "${dotnetProject}" "${path.resolve(configPath)}"`, { maxBuffer: 1024 * 500 }, (err, stdout) => {
```
then it works like normal. So my proposal is to either let maxBuffer be a config option in the json, [or possibly use process.stream](https://www.hacksparrow.com/nodejs/difference-between-spawn-and-exec-of-node-js-child-rocess.html) which seems like it might be better for this task.

Error:
```
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:357:14)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:273:13)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:150:17)
```

**Comment by svenheden** [comment]
Thanks @DrewRomanyk for the error report and tip on using `spawn()`!
